name: Playwright CI - Push/PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install
        sudo chown -R $(whoami) ./node_modules  # Ensure correct permissions for node_modules

    - name: Install Playwright browsers
      run: |
        sudo npx playwright install  # Run with sudo to ensure the Playwright binary installs correctly

    - name: Run Playwright tests
      run: npx playwright test

    - name: Upload error screenshots (if any)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: ./artifacts/error-screenshots

    - name: Upload Playwright report (if any)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: ./playwright-report
